modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/AppliedEnergistics/Applied-Energistics-2/issues"
[[mods]]
modId="appliedenergistics2"
version="${file.jarVersion}"
displayName="Applied Energistics 2"
displayURL="http://ae2.ae-mod.info"
logoFile="logo.png"
credits="AlgorithmX2"
authors="AlgorithmX2"
description="A Mod about Matter, Energy and using them to conquer the world.."
[[dependencies.appliedenergistics2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.appliedenergistics2]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
